name: CI Build

on: push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update apt
        run: sudo apt-get update

      - name: Clone the grug submodule
        run: git submodule update --init

      - name: Run the tests
        run: ./gradlew runGameTestServer --warning-mode=fail
