name: CI Build

on: push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update apt
        run: sudo apt-get update

      - name: Clone the grug submodule
        run: git submodule update --init

      # TODO: REMOVE!
      # - name: Install nasm
      #   run: sudo apt install nasm

      # TODO: REMOVE!
      - name: Print the gradlew version
        run: ./gradlew --version

      - name: Run the tests
        run: ./gradlew runGameTestServer
